apiVersion: v1
kind: Service
metadata:
  name: go-svc-template
spec:
  selector:
    app: go-svc-template
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-svc-template-deployment
spec:
  selector:
    matchLabels:
      app: go-svc-template
  replicas: 4
  template:
    metadata:
      labels:
        app: go-svc-template
    spec:
      containers:
        - name: go-svc-template
          image: registry.digitalocean.com/your_org/{{SERVICE}}:{{VERSION}}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: GO_SVC_TEMPLATE_SERVICE_NAME
              value: "go-svc-template"

            - name: GO_SVC_TEMPLATE_API_LISTEN_ADDRESS
              value: ":8080"

            - name: GO_SVC_TEMPLATE_LOG_CONFIG
              value: "prod"

            - name: GO_SVC_TEMPLATE_ENABLE_PPROF
              value: "true"

            - name: GO_SVC_TEMPLATE_NEW_RELIC_APP_NAME
              value: "go-svc-template (PROD)"

            - name: GO_SVC_TEMPLATE_NEW_RELIC_LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  name: newrelic
                  key: license_key

            - name: GO_SVC_TEMPLATE_RABBIT_URL
              valueFrom:
                secretKeyRef:
                  name: rabbit
                  key: url

            - name: GO_SVC_TEMPLATE_RABBIT_ROUTING_KEY
              value: "routing-key"

            - name: GO_SVC_TEMPLATE_RABBIT_EXCHANGE_NAME
              value: "events"

            - name: GO_SVC_TEMPLATE_RABBIT_EXCHANGE_DECLARE
              value: "true"

            - name: GO_SVC_TEMPLATE_RABBIT_EXCHANGE_DURABLE
              value: "true"

            - name: GO_SVC_TEMPLATE_RABBIT_BINDING_KEYS
              value: "routing-key"

            - name: GO_SVC_TEMPLATE_RABBIT_QUEUE_NAME
              value: "go-svc-template"

            - name: GO_SVC_TEMPLATE_RABBIT_QUEUE_DECLARE
              value: "true"

            - name: GO_SVC_TEMPLATE_RABBIT_QUEUE_DURABLE
              value: "true"

            - name: GO_SVC_TEMPLATE_RABBIT_QUEUE_AUTO_DELETE
              value: "false"

            - name: GO_SVC_TEMPLATE_RABBIT_QUEUE_EXCLUSIVE
              value: "false"

            - name: GO_SVC_TEMPLATE_RABBIT_NUM_CONSUMERS
              value: "10"
          resources:
            requests:
              memory: "512Mi"
              cpu: "256m"
            limits:
              memory: "1G"
              cpu: "512m"
          livenessProbe:
            httpGet:
              path: /health-check
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5
      imagePullSecrets:
      - name: registry-creds
